POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "tyler@litz.com",
    "password": "Tyler"
}

###

GET http://localhost:8080/api/character/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkbWwtYXBwIiwic3ViIjoibWFyaXNoYUByYXkuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX1BMQVlFUiIsImV4cCI6MTY1MTYzMDEzNn0.pMTOKrMvWmNc3FdIh1rAGd6Pn7hiqNtVN3pyxOcAtk8