POST http://localhost:8080/api/security/login
Content-Type: application/json

{
    "username": "tyler@litz.com",
    "password": "Tyler"
}

###

GET http://localhost:8080/api/character/campaign/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkbWwtYXBwIiwic3ViIjoidHlsZXJAbGl0ei5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2NTE2MjU4NDN9.AYibU-36T8YxbTnPIEQ9YfrS6ZWQlqaHCbOWZVpfbFo